In [18]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\23059\OneDrive\Desktop\Amiira\Y3S1\fyp\sample.csv")

In [19]:
import networkx as nx
import matplotlib.pyplot as plt

## New df

In [20]:
df_sample = df.iloc[:100]

## Data cleaning

## Feature encoding

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df_sample['type'])
label
df_sample.drop("type", axis=1, inplace=True)
df_sample["type"] = label

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df_sample['nameDest'])
label
df_sample.drop("nameDest", axis=1, inplace=True)
df_sample["nameDest"] = label

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df_sample['nameOrig'])
label
df_sample.drop("nameOrig", axis=1, inplace=True)
df_sample["nameOrig"] = label

C:\Users\23059\anaconda3\envs\test2\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\Users\23059\anaconda3\envs\test2\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\23059\anaconda3\envs\test2\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\23059\anaconda3\envs\test2\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
df_sample

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,type,nameDest,nameOrig
0,259,246917.44,0.00,0.00,3175848.97,3422766.41,0,0,1,19,32
1,161,165577.48,242080.31,407657.78,653770.69,488193.21,0,0,0,15,55
2,331,11147.81,21271.00,10123.19,0.00,0.00,0,0,3,72,86
3,304,3758.44,0.00,0.00,0.00,0.00,0,0,3,86,5
4,355,295770.07,0.00,0.00,429733.98,725504.05,0,0,1,38,63
...,...,...,...,...,...,...,...,...,...,...,...
95,371,193338.61,55760.00,249098.61,701871.95,508533.34,0,0,0,16,76
96,140,299851.25,18969.00,318820.25,0.00,0.00,0,0,0,40,35
97,1,11996.58,0.00,0.00,40255.00,0.00,0,0,4,12,82
98,323,107350.16,4217093.17,4324443.33,136320.02,28969.86,0,0,0,44,59
99,356,9479.80,7289.59,0.00,0.00,0.00,0,0,3,74,53

## Outliers

In [23]:
from scipy.stats import trim_mean

# Define the trimming fraction
trim_fraction = 0.1

# Calculate the trimmed mean for each column
trimmed_means = df_sample.apply(lambda x: trim_mean(x, trim_fraction))

# Replace the outliers with the trimmed mean
df_sample = df_sample.apply(lambda x: np.where(np.abs(x - np.mean(x)) > 2*np.std(x), trimmed_means[x.name], x))

## Class imbalance

In the context of network analysis, one way to handle class imbalance is to adjust the weights of the edges in the network. For example, you can assign higher weights to edges that correspond to fraudulent activities to increase their impact on the overall network structure

In [24]:
df_sample

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,type,nameDest,nameOrig
0,259.0,246917.44,0.00,0.00,3175848.97,3422766.41,0.0,0.0,1.0,19.0,32.0
1,161.0,165577.48,242080.31,407657.78,653770.69,488193.21,0.0,0.0,0.0,15.0,55.0
2,331.0,11147.81,21271.00,10123.19,0.00,0.00,0.0,0.0,3.0,72.0,86.0
3,304.0,3758.44,0.00,0.00,0.00,0.00,0.0,0.0,3.0,86.0,5.0
4,355.0,295770.07,0.00,0.00,429733.98,725504.05,0.0,0.0,1.0,38.0,63.0
...,...,...,...,...,...,...,...,...,...,...,...
95,371.0,193338.61,55760.00,249098.61,701871.95,508533.34,0.0,0.0,0.0,16.0,76.0
96,140.0,299851.25,18969.00,318820.25,0.00,0.00,0.0,0.0,0.0,40.0,35.0
97,1.0,11996.58,0.00,0.00,40255.00,0.00,0.0,0.0,4.0,12.0,82.0
98,323.0,107350.16,4217093.17,4324443.33,136320.02,28969.86,0.0,0.0,0.0,44.0,59.0
99,356.0,9479.80,7289.59,0.00,0.00,0.00,0.0,0.0,3.0,74.0,53.0

## Reinforcement Learning

In [25]:
import pandas as pd
import numpy as np

# Define the state, action, and reward functions
def get_state(df_sample, t):
    state =df_sample.iloc[t, [1,2,3,4,5,8]].values # use relevant columns from dataset
    return state

def get_action(state):
    # Flag transaction as fraudulent if the transaction amount is greater than 200,000
    if state[1] > 200000:
        action = 1
    else:
        action = 0
    return action

def get_reward(action, isFraud):
    if action == 1 and isFraud == 1:
        reward = 1
    elif action == 1 and isFraud == 0:
        reward = -1
    else:
        reward = 0
    return reward

# Define the Q-learning algorithm
def q_learning(df_sample, alpha, gamma, epsilon, max_steps):
    # Initialize Q table
    q_table = np.zeros((num_states, num_actions))

    # Loop through each time step in the data
    for t in range(max_steps):
        state = get_state(df_sample, t)

        # Epsilon-greedy policy
        if np.random.uniform() < epsilon:
            action = np.random.choice(num_actions)
        else:
            qstate = get_state(df_sample, t)
            state_int = state.astype(int) # convert state to integers
            q_values = q_table[state_int, :]

            action = np.argmax(q_values)

        # Take the chosen action and observe the new state and reward
        new_state = get_state(df_sample, t+1)
        isFraud = df_sample.iloc[t, -2] # get isFraud label
        reward = get_reward(action, isFraud)

        # Update Q table
        old_value = q_table[state, action]
        next_max = np.max(q_table[new_state, :])
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

    return q_table

# Run the Q-learning algorithm
alpha = 0.1
gamma = 0.99
epsilon = 0.1
max_steps = len(df_sample) - 1
num_states = len(df_sample.iloc[0, [1,2,3,4,5,8]].unique()) # number of unique state combinations
num_actions = 2 # flag as fraudulent or not
q_table = q_learning(df_sample, alpha, gamma, epsilon, max_steps)

IndexError: index 246917 is out of bounds for axis 0 with size 5

In [28]:
def q_learning(df_sample, alpha, gamma, epsilon, max_steps):
    # Initialize Q table
    q_table = np.zeros((num_states, num_actions))

    # Loop through each time step in the data
    for t in range(max_steps):
        state = get_state(df_sample, t)

        # Epsilon-greedy policy
        if np.random.uniform() < epsilon:
            action = np.random.choice(num_actions)
        else:
            qstate = get_state(df_sample, t)
            state_int = tuple(map(int, state)) # convert state to tuple of integers
            q_values = q_table[state_int, :]

            action = np.argmax(q_values)

        # Take the chosen action and observe the new state and reward
        new_state = get_state(df_sample, t+1)
        isFraud = df_sample.iloc[t, -2] # get isFraud label
        reward = get_reward(action, isFraud)

        # Update Q table
        old_value = q_table[state_int, action]
        next_max = np.max(q_table[tuple(map(int, new_state)), :])
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state_int, action] = new_value

    return q_table

Choose a reinforcement learning algorithm: There are many different reinforcement learning algorithms that you could use for fraud detection, including Q-learning, SARSA, and actor-critic methods. You will need to choose an algorithm that is appropriate for